/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author cesar
 */
public class pArticulos extends javax.swing.JPanel {

    /**
     * Creates new form pArticulos
     */
    public pArticulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        btnPRev = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnPCD = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnPTe = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnPObr = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnPDoc = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnPLibro = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        contenedorArt = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(730, 560));

        menu.setBackground(new java.awt.Color(94, 96, 206));
        menu.setPreferredSize(new java.awt.Dimension(730, 110));

        btnPRev.setBackground(new java.awt.Color(94, 96, 206));
        btnPRev.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPRev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPRevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPRevMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPRevMousePressed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Revista");

        javax.swing.GroupLayout btnPRevLayout = new javax.swing.GroupLayout(btnPRev);
        btnPRev.setLayout(btnPRevLayout);
        btnPRevLayout.setHorizontalGroup(
            btnPRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPRevLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btnPRevLayout.setVerticalGroup(
            btnPRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPRevLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPCD.setBackground(new java.awt.Color(94, 96, 206));
        btnPCD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPCD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPCDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPCDMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPCDMousePressed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CD");

        javax.swing.GroupLayout btnPCDLayout = new javax.swing.GroupLayout(btnPCD);
        btnPCD.setLayout(btnPCDLayout);
        btnPCDLayout.setHorizontalGroup(
            btnPCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPCDLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(27, 27, 27))
        );
        btnPCDLayout.setVerticalGroup(
            btnPCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPCDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPTe.setBackground(new java.awt.Color(94, 96, 206));
        btnPTe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPTe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPTeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPTeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPTeMousePressed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tesis");

        javax.swing.GroupLayout btnPTeLayout = new javax.swing.GroupLayout(btnPTe);
        btnPTe.setLayout(btnPTeLayout);
        btnPTeLayout.setHorizontalGroup(
            btnPTeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPTeLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(29, 29, 29))
        );
        btnPTeLayout.setVerticalGroup(
            btnPTeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPTeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPObr.setBackground(new java.awt.Color(94, 96, 206));
        btnPObr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPObr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPObrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPObrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPObrMousePressed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Obras");

        javax.swing.GroupLayout btnPObrLayout = new javax.swing.GroupLayout(btnPObr);
        btnPObr.setLayout(btnPObrLayout);
        btnPObrLayout.setHorizontalGroup(
            btnPObrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPObrLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        btnPObrLayout.setVerticalGroup(
            btnPObrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPObrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnPDoc.setBackground(new java.awt.Color(94, 96, 206));
        btnPDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnPDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPDocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPDocMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPDocMousePressed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Documentos");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("informativos");

        javax.swing.GroupLayout btnPDocLayout = new javax.swing.GroupLayout(btnPDoc);
        btnPDoc.setLayout(btnPDocLayout);
        btnPDocLayout.setHorizontalGroup(
            btnPDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPDocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnPDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        btnPDocLayout.setVerticalGroup(
            btnPDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPDocLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPLibro.setBackground(new java.awt.Color(94, 96, 206));
        btnPLibro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPLibroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPLibroMousePressed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Libro");

        javax.swing.GroupLayout btnPLibroLayout = new javax.swing.GroupLayout(btnPLibro);
        btnPLibro.setLayout(btnPLibroLayout);
        btnPLibroLayout.setHorizontalGroup(
            btnPLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPLibroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btnPLibroLayout.setVerticalGroup(
            btnPLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(btnPLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPRev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnPCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPTe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnPObr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnPDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPObr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPTe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPCD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPRev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnPLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        contenedorArt.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenedorArtLayout = new javax.swing.GroupLayout(contenedorArt);
        contenedorArt.setLayout(contenedorArtLayout);
        contenedorArtLayout.setHorizontalGroup(
            contenedorArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenedorArtLayout.setVerticalGroup(
            contenedorArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
            .addComponent(contenedorArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPRevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPRevMouseEntered
        if(btnPRev.getBackground().getRGB() == -83144217)
        setColor(btnPRev);
    }//GEN-LAST:event_btnPRevMouseEntered

    private void btnPRevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPRevMouseExited
        if(btnPCD.getBackground().getRGB() != -83144217 || btnPDoc.getBackground().getRGB() != -83144217
            || btnPObr.getBackground().getRGB() != -83144217 || btnPLibro.getBackground().getRGB() != -83144217
            || btnPTe.getBackground().getRGB() != -83144217)
        resetColor(btnPRev);
    }//GEN-LAST:event_btnPRevMouseExited

    private void btnPRevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPRevMousePressed
       resetColor(btnPCD);
       resetColor(btnPDoc);
       resetColor(btnPLibro);
       resetColor(btnPObr);
       setColor(btnPRev); 
       resetColor(btnPTe);
        
        pRevistas pR = new pRevistas();
        pR.setSize(730, 560);
        pR.setLocation(0,0);
        
        contenedorArt.removeAll();
        contenedorArt.add(pR, BorderLayout.CENTER);
        contenedorArt.revalidate();
        contenedorArt.repaint(); 
    }//GEN-LAST:event_btnPRevMousePressed

    private void btnPCDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCDMouseEntered
        if(btnPCD.getBackground().getRGB() == -83144217)
        setColor(btnPCD);
    }//GEN-LAST:event_btnPCDMouseEntered

    private void btnPCDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCDMouseExited
        if(btnPLibro.getBackground().getRGB() != -83144217 || btnPDoc.getBackground().getRGB() != -83144217
            || btnPObr.getBackground().getRGB() != -83144217 || btnPRev.getBackground().getRGB() != -83144217
            || btnPTe.getBackground().getRGB() != -83144217)
        resetColor(btnPCD);
    }//GEN-LAST:event_btnPCDMouseExited

    private void btnPCDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCDMousePressed
       setColor(btnPCD);
       resetColor(btnPDoc);
       resetColor(btnPLibro);
       resetColor(btnPObr);
       resetColor(btnPRev); 
       resetColor(btnPTe);
        
        pCd pC = new pCd();
        pC.setSize(730, 560);
        pC.setLocation(0,0);

        contenedorArt.removeAll();
        contenedorArt.add(pC, BorderLayout.CENTER);
        contenedorArt.revalidate();
        contenedorArt.repaint(); 
    }//GEN-LAST:event_btnPCDMousePressed

    private void btnPTeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPTeMouseEntered
         if(btnPTe.getBackground().getRGB() == -83144217)
        setColor(btnPTe);
    }//GEN-LAST:event_btnPTeMouseEntered

    private void btnPTeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPTeMouseExited
        if(btnPLibro.getBackground().getRGB() != -83144217 || btnPDoc.getBackground().getRGB() != -83144217
            || btnPObr.getBackground().getRGB() != -83144217 || btnPRev.getBackground().getRGB() != -83144217
            || btnPCD.getBackground().getRGB() != -83144217)
        resetColor(btnPTe);
    }//GEN-LAST:event_btnPTeMouseExited

    private void btnPTeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPTeMousePressed
       resetColor(btnPCD);
       resetColor(btnPDoc);
       resetColor(btnPLibro);
       resetColor(btnPObr);
       resetColor(btnPRev); 
       setColor(btnPTe);
        
        pTesis pT = new pTesis();
        pT.setSize(730, 560);
        pT.setLocation(0,0);

        contenedorArt.removeAll();
        contenedorArt.add(pT, BorderLayout.CENTER);
        contenedorArt.revalidate();
        contenedorArt.repaint(); 
    }//GEN-LAST:event_btnPTeMousePressed

    private void btnPObrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPObrMouseEntered
         if(btnPObr.getBackground().getRGB() == -83144217)
        setColor(btnPObr);
    }//GEN-LAST:event_btnPObrMouseEntered

    private void btnPObrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPObrMouseExited
        if(btnPLibro.getBackground().getRGB() != -83144217 || btnPDoc.getBackground().getRGB() != -83144217
            || btnPTe.getBackground().getRGB() != -83144217 || btnPRev.getBackground().getRGB() != -83144217
            || btnPCD.getBackground().getRGB() != -83144217)
        resetColor(btnPObr);
    }//GEN-LAST:event_btnPObrMouseExited

    private void btnPObrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPObrMousePressed
       resetColor(btnPCD);
       resetColor(btnPDoc);
       resetColor(btnPLibro);
       setColor(btnPObr);
       resetColor(btnPRev); 
       resetColor(btnPTe);
        
        pObras pO = new pObras();
        pO.setSize(730, 560);
        pO.setLocation(0,0);

        contenedorArt.removeAll();
        contenedorArt.add(pO, BorderLayout.CENTER);
        contenedorArt.revalidate();
        contenedorArt.repaint();
    }//GEN-LAST:event_btnPObrMousePressed

    private void btnPDocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPDocMouseEntered
         if(btnPDoc.getBackground().getRGB() == -83144217)
        setColor(btnPDoc);
    }//GEN-LAST:event_btnPDocMouseEntered

    private void btnPDocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPDocMouseExited
         if(btnPLibro.getBackground().getRGB() != -83144217 || btnPObr.getBackground().getRGB() != -83144217
            || btnPTe.getBackground().getRGB() != -83144217 || btnPRev.getBackground().getRGB() != -83144217
            || btnPCD.getBackground().getRGB() != -83144217)
        resetColor(btnPDoc);
    }//GEN-LAST:event_btnPDocMouseExited

    private void btnPDocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPDocMousePressed
       resetColor(btnPCD);
       setColor(btnPDoc);
       resetColor(btnPLibro);
       resetColor(btnPObr);
       resetColor(btnPRev); 
       resetColor(btnPTe);
        
        pDocumenInfo pD = new pDocumenInfo();
        pD.setSize(730, 560);
        pD.setLocation(0,0);

        contenedorArt.removeAll();
        contenedorArt.add(pD, BorderLayout.CENTER);
        contenedorArt.revalidate();
        contenedorArt.repaint();
    }//GEN-LAST:event_btnPDocMousePressed

    private void btnPLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPLibroMouseEntered
        if(btnPLibro.getBackground().getRGB() == -83144217)
        setColor(btnPLibro);
    }//GEN-LAST:event_btnPLibroMouseEntered

    private void btnPLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPLibroMouseExited
        if(btnPCD.getBackground().getRGB() != -83144217 || btnPDoc.getBackground().getRGB() != -83144217
            || btnPObr.getBackground().getRGB() != -83144217 || btnPRev.getBackground().getRGB() != -83144217
            || btnPTe.getBackground().getRGB() != -83144217)
        resetColor(btnPLibro);
    }//GEN-LAST:event_btnPLibroMouseExited

    private void btnPLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPLibroMousePressed
       resetColor(btnPCD);
       resetColor(btnPDoc);
       setColor(btnPLibro);
       resetColor(btnPObr);
       resetColor(btnPRev); 
       resetColor(btnPTe);
        
        pLibros pL = new pLibros();
        pL.setSize(730, 560);
        pL.setLocation(0,0);

        contenedorArt.removeAll();
        contenedorArt.add(pL, BorderLayout.CENTER);
        contenedorArt.revalidate();
        contenedorArt.repaint(); 
    }//GEN-LAST:event_btnPLibroMousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(105, 48, 195));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(94, 96, 206));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPCD;
    private javax.swing.JPanel btnPDoc;
    private javax.swing.JPanel btnPLibro;
    private javax.swing.JPanel btnPObr;
    private javax.swing.JPanel btnPRev;
    private javax.swing.JPanel btnPTe;
    private javax.swing.JPanel contenedorArt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
