/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JPanel;

/**
 *
 * @author cesar
 */
public class PrincipalPanel extends javax.swing.JFrame {
    int xMouse;
    int yMouse;

    Connection reg;

    /**
     * Creates new form PrincipalPanel
     */
    public PrincipalPanel() {
        initComponents();
        
        pBienvenida pBv = new pBienvenida();
        
        pBv.setSize(750, 430);
        pBv.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(pBv, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        btnArticulos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnMora = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnDevoluciones = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnPrestamos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBienvenida = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1020, 640));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fondo.setPreferredSize(new java.awt.Dimension(900, 650));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(94, 96, 206));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnArticulos.setBackground(new java.awt.Color(94, 96, 206));
        btnArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnArticulos.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArticulosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArticulosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnArticulosMousePressed(evt);
            }
        });
        btnArticulos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Articulos");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        btnArticulos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 16, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/books (2).png"))); // NOI18N
        btnArticulos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        menu.add(btnArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, 50));

        btnMora.setBackground(new java.awt.Color(94, 96, 206));
        btnMora.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnMora.setPreferredSize(new java.awt.Dimension(221, 60));
        btnMora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMoraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMoraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMoraMousePressed(evt);
            }
        });
        btnMora.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mora");
        btnMora.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atrasado.png"))); // NOI18N
        btnMora.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        menu.add(btnMora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 180, 50));

        btnDevoluciones.setBackground(new java.awt.Color(94, 96, 206));
        btnDevoluciones.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnDevoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDevolucionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDevolucionesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDevolucionesMousePressed(evt);
            }
        });
        btnDevoluciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Devolucion");
        btnDevoluciones.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja-de-devolucion.png"))); // NOI18N
        btnDevoluciones.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        menu.add(btnDevoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 180, 50));

        btnPrestamos.setBackground(new java.awt.Color(94, 96, 206));
        btnPrestamos.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrestamosMousePressed(evt);
            }
        });
        btnPrestamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prestamos");
        btnPrestamos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pedir-prestado.png"))); // NOI18N
        btnPrestamos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        menu.add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, -1));

        btnBienvenida.setBackground(new java.awt.Color(94, 96, 206));
        btnBienvenida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBienvenida.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnBienvenida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBienvenidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBienvenidaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBienvenidaMousePressed(evt);
            }
        });
        btnBienvenida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bienvenida");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        btnBienvenida.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 24, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/house.png"))); // NOI18N
        btnBienvenida.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        menu.add(btnBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, -1));

        fondo.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 650));

        header.setBackground(new java.awt.Color(94, 96, 206));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(72, 191, 227));
        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel1.setText("Biblioteca amigos de Don Bosco");
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        header.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 380, 5));

        fondo.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 90));
        fondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setPreferredSize(new java.awt.Dimension(763, 560));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        fondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 720, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArticulosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticulosMouseEntered
          if(btnArticulos.getBackground().getRGB() == -83144217)
        setColor(btnArticulos);
    }//GEN-LAST:event_btnArticulosMouseEntered

    private void btnArticulosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticulosMouseExited
       if(btnPrestamos.getBackground().getRGB() != -83144217 || btnMora.getBackground().getRGB() != -83144217
            || btnDevoluciones.getBackground().getRGB() != -83144217 || btnBienvenida.getBackground().getRGB() != -83144217 )
        resetColor(btnArticulos);
    }//GEN-LAST:event_btnArticulosMouseExited

    private void btnArticulosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticulosMousePressed
        setColor(btnArticulos);
        resetColor(btnPrestamos);
        resetColor(btnMora);
        resetColor(btnDevoluciones);
        resetColor(btnBienvenida);
        
        // Abrir sección
        pArticulos pAr = new pArticulos();
        pAr.setSize(730, 560);
        pAr.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(pAr, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint(); 
    }//GEN-LAST:event_btnArticulosMousePressed

    private void btnPrestamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseEntered
             if(btnPrestamos.getBackground().getRGB() == -83144217)
        setColor(btnPrestamos);
    }//GEN-LAST:event_btnPrestamosMouseEntered

    private void btnPrestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseExited
       if(btnArticulos.getBackground().getRGB() != -83144217 || btnMora.getBackground().getRGB() != -83144217
            || btnDevoluciones.getBackground().getRGB() != -83144217 || btnBienvenida.getBackground().getRGB() != -83144217)
        resetColor(btnPrestamos);
    }//GEN-LAST:event_btnPrestamosMouseExited

    private void btnPrestamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMousePressed
         resetColor(btnArticulos);
        setColor(btnPrestamos);
        resetColor(btnMora);
        resetColor(btnDevoluciones);
        resetColor(btnBienvenida);
        
        // Abrir sección
        pPrestamos pP = new pPrestamos();
        pP.setSize(730, 560);
        pP.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(pP, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint(); 
    }//GEN-LAST:event_btnPrestamosMousePressed

    private void btnMoraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoraMouseEntered
            if(btnMora.getBackground().getRGB() == -83144217)
        setColor(btnMora);
    }//GEN-LAST:event_btnMoraMouseEntered

    private void btnMoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoraMouseExited
        if(btnArticulos.getBackground().getRGB() != -83144217 || btnPrestamos.getBackground().getRGB() != -83144217
            || btnDevoluciones.getBackground().getRGB() != -83144217 || btnBienvenida.getBackground().getRGB() != -83144217)
        resetColor(btnMora);
    }//GEN-LAST:event_btnMoraMouseExited

    private void btnMoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoraMousePressed
        resetColor(btnArticulos);
        resetColor(btnPrestamos);
        setColor(btnMora);
        resetColor(btnDevoluciones);
        resetColor(btnBienvenida);
        
        // Abrir sección
        pMora pM = new pMora();
        pM.setSize(730, 560);
        pM.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(pM, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint(); 
    }//GEN-LAST:event_btnMoraMousePressed

    private void btnDevolucionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolucionesMouseEntered
             if(btnDevoluciones.getBackground().getRGB() == -83144217)
        setColor(btnDevoluciones);
    }//GEN-LAST:event_btnDevolucionesMouseEntered

    private void btnDevolucionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolucionesMouseExited
        if(btnArticulos.getBackground().getRGB() != -83144217 || btnPrestamos.getBackground().getRGB() != -83144217
            || btnMora.getBackground().getRGB() != -83144217 || btnBienvenida.getBackground().getRGB() != -83144217)
        resetColor(btnDevoluciones);
    }//GEN-LAST:event_btnDevolucionesMouseExited

    private void btnDevolucionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolucionesMousePressed
        resetColor(btnArticulos);
        resetColor(btnPrestamos);
        resetColor(btnMora);
        setColor(btnDevoluciones);
        resetColor(btnBienvenida);
        // Abrir sección
        pDevoluciones pD = new pDevoluciones();
        pD.setSize(730, 560);
        pD.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(pD, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint(); 
    }//GEN-LAST:event_btnDevolucionesMousePressed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void btnBienvenidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBienvenidaMouseEntered
         if(btnBienvenida.getBackground().getRGB() == -83144217)
        setColor(btnBienvenida);
    }//GEN-LAST:event_btnBienvenidaMouseEntered

    private void btnBienvenidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBienvenidaMouseExited
             if(btnArticulos.getBackground().getRGB() != -83144217 || btnPrestamos.getBackground().getRGB() != -83144217
            || btnMora.getBackground().getRGB() != -83144217 || btnDevoluciones.getBackground().getRGB() != -83144217 )
        resetColor(btnBienvenida);
    }//GEN-LAST:event_btnBienvenidaMouseExited

    private void btnBienvenidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBienvenidaMousePressed
        resetColor(btnArticulos);
        resetColor(btnPrestamos);
        resetColor(btnMora);
        resetColor(btnDevoluciones);
        setColor(btnBienvenida);
        
        // Abrir sección
        pBienvenida pB = new pBienvenida();
        pB.setSize(730, 560);
        pB.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(pB, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint(); 
    }//GEN-LAST:event_btnBienvenidaMousePressed

    /**
     * @param args the command line arguments
     */
    
     void setColor(JPanel panel){
        panel.setBackground(new Color(105, 48, 195));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(94, 96, 206));
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnArticulos;
    private javax.swing.JPanel btnBienvenida;
    private javax.swing.JPanel btnDevoluciones;
    private javax.swing.JPanel btnMora;
    private javax.swing.JPanel btnPrestamos;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
